"""Initial migration

Revision ID: 83af7504fdf4
Revises: 
Create Date: 2025-11-30 23:07:59.016822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83af7504fdf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cappers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cappers_id'), 'cappers', ['id'], unique=False)
    op.create_index(op.f('ix_cappers_name'), 'cappers', ['name'], unique=True)
    op.create_table('telegram_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_queue_id'), 'telegram_queue', ['id'], unique=False)
    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capper_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('match_key', sa.String(), nullable=True),
    sa.Column('pick_text', sa.String(), nullable=True),
    sa.Column('units_risked', sa.Float(), nullable=True),
    sa.Column('odds', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('original_image_path', sa.String(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['capper_id'], ['cappers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picks_id'), 'picks', ['id'], unique=False)
    op.create_index(op.f('ix_picks_match_key'), 'picks', ['match_key'], unique=False)
    op.create_index(op.f('ix_picks_sport'), 'picks', ['sport'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_picks_sport'), table_name='picks')
    op.drop_index(op.f('ix_picks_match_key'), table_name='picks')
    op.drop_index(op.f('ix_picks_id'), table_name='picks')
    op.drop_table('picks')
    op.drop_index(op.f('ix_telegram_queue_id'), table_name='telegram_queue')
    op.drop_table('telegram_queue')
    op.drop_index(op.f('ix_cappers_name'), table_name='cappers')
    op.drop_index(op.f('ix_cappers_id'), table_name='cappers')
    op.drop_table('cappers')
    # ### end Alembic commands ###
